//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dataEntryform
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoTable
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string address { get; set; }
        public decimal mobile_no { get; set; }
        public string email { get; set; }
    }
}
